"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ["rbhs-reunion-api.vercel.app", "localhost","127.0.0.1:8000" ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',  # optional for frontend integration
    'cloudinary',
    'cloudinary_storage',
    'accounts',
    'payments',
    'tickets',
    'notice',
    'stats',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # for whitenosie 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # if using cors
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.getenv('DB_SSLMODE', 'require'),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Timezone settings
TIME_ZONE = 'Asia/Dhaka'
USE_TZ = True
USE_L10N = True
USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ✅ where collectstatic will put files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cloudinary setup
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.getenv('cloud_name'),
    api_key=os.getenv('api_key'),
    api_secret=os.getenv('api_secret')
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'





# add rate limiting / throttling
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Rate limiting: authenticated users and anonymous users
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '200/min',
        'anon': '100/min',
    },
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),

}

AUTH_USER_MODEL = 'accounts.User'

JAZZMIN_SETTINGS = {
    "site_title": "RBMB Reunion Admin",
    "site_header": "RBMB Reunion",
    "site_brand": "RBMB Reunion",
    "welcome_sign": "Welcome to RBMB Reunion Admin",
    
    # Custom CSS and JS for dashboard
    "custom_css": None,
    "custom_js": None,
    
    # Top menu links
    "topmenu_links": [
        # {"name": "Dashboard Stats", "url": "/api/stats/admin-dashboard/", "new_window": True},
        # {"name": "Registration Stats", "url": "/api/stats/registration-stats/", "new_window": True},
        # {"name": "Donation Stats", "url": "/api/stats/donation-stats/", "new_window": True},
    ],
    
    # Icons for models
    "icons": {
        "accounts.user": "fas fa-user",
        "accounts.user": "fas fa-users",
        "tickets.ticket": "fas fa-ticket-alt",
        "payments.payment": "fas fa-money-bill-wave",
        "notice.notice": "fas fa-bullhorn",
        "auth.group": "fas fa-users",
        "auth.permission": "fas fa-lock",
    },

    # Custom ordering
    "order_with_respect_to": ["accounts", "payments", "tickets", "notice"],
    
  
    
    # Top menu items
    "topmenu": [
        {"name": "Users", "app": "accounts", "model": "user"},
        {"name": "Payments", "app": "payments", "model": "payment"},
        {"name": "Tickets", "app": "tickets", "model": "ticket"},
        {"name": "Notices", "app": "notice", "model": "notice"},
    ],

    # Hide apps/models if needed
    "hide_apps": [],
    "hide_models": [],
    
    # UI customization
    "theme": "default",
    "dark_mode_theme": "darkly",
    
    # Sidebar customization
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Related modal
    "related_modal_active": True,
    
    # Custom colors
    "brand_colors": {
        "primary": "#2E86AB",
        "secondary": "#A23B72",
        "success": "#F18F01",
        "info": "#C73E1D",
        "warning": "#F18F01",
        "danger": "#C73E1D",
        "light": "#F8F9FA",
        "dark": "#212529",
    },
    
    # Logo
    "logo": None,
    "logo_icon": None,
    
    # Copyright
    "copyright": "RBMB Reunion 2025",
}


SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True  # only in production
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True



CSRF_TRUSTED_ORIGINS = [
        "https://rbhs-reunion-api.vercel.app",
    ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8080",
    "https://rbhs-reunion.vercel.app",
    "https://rbmbians.com",
    "https://www.rbmbians.com",
]

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False